app:
    build: .
    image: ipython

    container_name: ipython_container

    hostname: ipython
    privileged: true
    restart: always
    stdin_open: true
    tty: true

    volumes:
     - ~/Documents:/root

    expose:
     - "8888:8888"


